
version: '3.8'

services:
  web:
    build: .
    image: mywebapp
    ports:
      - "127.0.0.1:15000:5000"  # Restrict port to localhost 127.0.0.1
    depends_on:
      - db
    networks:
      - frontend
    read_only: true
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    pids_limit: 100
    env_file:
      - .env

  db:
    image: postgres:13
    restart: always
    networks:
      - backend
    env_file:
      - .env
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid

networks:
  frontend:
  backend:
