name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t mywebapp-secure .

    - name: Run container and check health
      run: |
        docker network create secure-net
        docker run -d --name test-app --network secure-net \
          --read-only --tmpfs /tmp \
          --cap-drop ALL \
          -p 5000:5000 mywebapp-secure
        sleep 5
        curl --fail http://localhost:5000/health
